### ISSUE TITLE
assertion failure on sqlite connection garbage collection

### ISSUE THREAD

**Issue by obmarg** [mmzeeman/esqlite#20]
I've been playing about with esqlite and Sqlitex (an Elixir wrapper for sqlite) quite a bit lately.  When I run the Sqlitex tests I frequently get assertion failures coming from here: https://github.com/mmzeeman/esqlite/blob/master/c_src/queue.c#L170

I've tried to do a bit of debugging using this patch:

```
diff --git a/c_src/esqlite3_nif.c b/c_src/esqlite3_nif.c
index 87787f7..a2ecbef 100644
--- a/c_src/esqlite3_nif.c
+++ b/c_src/esqlite3_nif.c
@@ -205,30 +206,32 @@ command_create()
 /*
  *
  */
-static void
+static void
 destruct_esqlite_connection(ErlNifEnv *env, void *arg)
 {
     esqlite_connection *db = (esqlite_connection *) arg;
     esqlite_command *cmd = command_create();
-
-    /* Send the stop command
+
+    printf("Destructing 0x%08X\n", (int)db);
+
+    /* Send the stop command
      */
     cmd->type = cmd_stop;
     queue_push(db->commands, cmd);
     queue_send(db->commands, cmd);
-
-    /* Wait for the thread to finish
-     */
+
     enif_thread_join(db->tid, NULL);
     enif_thread_opts_destroy(db->opts);
      */
     queue_destroy(db->commands);

     if(db->db)
-        sqlite3_close_v2(db->db);
+      sqlite3_close_v2(db->db);
+
+    printf("Destructed 0x%08X\n", (int)db);
 }
```

From which I get the output:

> Constructed 0x16145540
Constructed 0x18601730
Destructing 0x18601730
Thread ended 0x18601730
Destructed 0x18601730
Constructed 0x18601730
Destructing 0x18601730
Thread ended 0x18601730
Destructed 0x18601730
Constructed 0x18601730
Destructing 0x18601730
Thread ended 0x18601730
Destructed 0x18601730
Constructed 0x18601730
Destructing 0x18601730
Thread ended 0x18601730
Destructed 0x18601730
Constructed 0x162000D8
Destructing 0x162000D8
Thread ended 0x162000D8
Destructed 0x162000D8
Constructed 0x18601730
Destructing 0x18601730
Thread ended 0x18601730
Destructed 0x18601730
Constructed 0x18601730
Destructing 0x18601730
Thread ended 0x18601730
Destructed 0x18601730
Constructed 0x16141320
Destructing 0x16141320
Thread ended 0x16141320
Destructed 0x16141320
Constructed 0x16141320
Destructing 0x16141320
Thread ended 0x16141320
Destructed 0x16141320
Constructed 0x16141320
Destructing 0x16141320
Thread ended 0x16141320
Destructed 0x16141320
Constructed 0x162000D8
Destructing 0x162000D8
Destructing 0x162000D8
Assertion failed: (queue->message == NULL && "Attempting to send multiple messages."), function queue_send, file c_src/queue.c, line 170.
[1]    90976 abort      mix test

If you look towards the end, it appears `destruct_esqlite_connection` was called twice for the same connection.  As I understand it this function is called from the erlang GC, so I'm not sure how it manages to get called twice, but it does appear to be happening.

I'm running this on a mac with:

> Erlang/OTP 17 [erts-6.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
> Interactive Elixir (1.0.2) - press Ctrl+C to exit (type h() ENTER for help)

**Comment by jazzyb** [comment]
Can you point to a gist or repo with the tests that are causing the assertion failures?

**Comment by obmarg** [comment]
@jazzyb I'm just running `mix test` in a clean copy of https://github.com/mmmries/sqlitex at commit 68343859.

It doesn't happen every time, but it does happen frequently - maybe about 10% of the times I run `mix test` I get this assertion failed error.

**Comment by jazzyb** [comment]
Strange.  I haven't seen that error on Ubuntu or FreeBSD.  Do you know which of the OTP 17 releases you are using?  Are you on Yosemite (10.10.3 or 10.10.4)?

**Comment by obmarg** [comment]
Yeah, it is a strange one - figured it wouldn't happen for everyone or it'd likely have been found or fixed by now.

Yosemite 10.10.3.
Erlang & Elixir are both from homebrew.  Homebrew says it's Erlang 17.4.
Erlang just says 17:

```
erlang:system_info(otp_release).
"17"
```

I did wonder if this could be something to do with the `destruct_esqlite_connection` function calling `enif_thread_join` - presumably this blocks and could cause the "strange behaviour" mentioned in the [NIF documentation](http://www.erlang.org/doc/man/erl_nif.html):

> A native function that do lengthy work before returning will degrade responsiveness of the VM, and may cause miscellaneous strange behaviors. Such strange behaviors include, but are not limited to, extreme memory usage, and bad load balancing between schedulers. Strange behaviors that might occur due to lengthy work may also vary between OTP releases.

**Comment by jazzyb** [comment]
It certainly could be the scheduler; however, I understand the library was designed to work with the BEAM scheduler.  Furthermore, unless you're performing queries across thousands of rows -- which the Sqlitex tests do not do -- I wouldn't expect execution to even stay in the NIF long enough to throw-off the scheduler.

I'll start investigating the issue this evening.  Thanks for bringing this up.

**Comment by jazzyb** [comment]
One final question:  Was there any pattern to *which* Sqlitex test triggered the assertion, or did it seem random?

**Comment by obmarg** [comment]
@jazzyb Thanks, would be great to get to the bottom of this.

It's pretty much always in SqlitexTest, but other than that it seems pretty random precisely which test fails.  So far I have seen it fail in "it inserts Erlang datetime tuples", "it inserts nil", "decimal types with scale and precision" and "that it returns an error for a bad query".  Probably others as well, but I haven't been running the tests with `--trace` most of the time.

Around the scheduler: the majority of the work does run on a background thread, but (as far as I understand) `destruct_sqlite_connection` (which calls the `queue_send` function with the assert) will run on be called on an erlang thread by the GC.  [On this line](https://github.com/mmzeeman/esqlite/blob/master/c_src/esqlite3_nif.c#L221) it calls enif_thread_join to wait for the background thread to finish.  That's kind of where I imagined the issue to arise - if the background thread didn't stop quickly.

If you look at my `printf` output in the report you'll notice some "Thread Finished" messages that I added as well - the second Destruct occurs before both "Thread Finished" and "Thread Destructed", which implies that the first destruction has stopped executing _somewhere_ before the end of the function.

But anyway, this is just a guess - I definitely don't know enough about Erlangs garbage collection and/or scheduler to say more than that.

**Comment by jazzyb** [comment]
Just an quick update:  I've just got a VM setup, and I have verified that I see the same error on OS X 10.10 with Erlang 17.5 and Elixir 1.0.5.

**Comment by jazzyb** [comment]
I think I've isolated the Sqlitex test that is causing the crash and have a temporary work-around for the tests.

This test is causing the crash although I don't yet know why:

```elixir
  test "server query times out" do
    {:ok, conn} = Sqlitex.Server.start_link(":memory:")
    assert match?({:timeout, _},
      catch_exit(Sqlitex.Server.query(conn, "SELECT * FROM sqlite_master", timeout: 0)))
  end
```

What this test is doing is making sure that the server will timeout on long queries.  The thing about timeouts is that they give up waiting on a response, but the server will continue to process the request and eventually try to send a response which will just sit in the caller's mailbox because the caller is no longer waiting on it.  I think the crash is happening somewhere at this point because the NIF is still trying to process the request when the process is killed by the end of the test.  I don't know why that should be so, but it looks like that is what is happening.  I'll need to spend more time later looking through the esqlite code to determine the actual cause.

In the meantime I may have a work-around to at least get the Sqlitex tests to pass.  @obmarg, can you pull [my assertion-error branch](https://github.com/jazzyb/sqlitex/tree/assertion-error) to your system and see if it fixes the issue for you.  It appears to fix the issue on my end.  The change simply waits for the timed-out response before ending the test.  If that does fix the issue, then the good news is that you probably won't run into this error in your own code unless you're using the Sqlitex.Server and your query times-out.

One other thing about the addresses you saw being repeated in your original comment:  I saw many connection addresses being reused for runs that didn't crash.  I don't think that is necessarily an issue; the esqlite code looks like it's just reusing memory for different database connections.

**Comment by obmarg** [comment]
Thanks for taking the time to investigate this so quickly, I really appreciate it.

I'll pull down that branch and see later on, just quickly wanted to respond to your last paragraph:  it wasn't addresses being re-used that I thought was a problem.  It was addresses being destructed twice without being constructed in the middle.  Might be clearer if I cut down my sample output above to just the relevant address:

> Constructed 0x162000D8
Destructing 0x162000D8
Thread ended 0x162000D8
Destructed 0x162000D8
Constructed 0x162000D8
Destructing 0x162000D8
Destructing 0x162000D8

The first 4 lines are fine - address is constructed, destructing starts, the thread ends and then destructing finishes.  It's the next three lines that worry me - construction, destruction starts, destruction starts again.  The assertion failure happens immediately after that last line, so I'd be seriously surprised if this was not at least related to the problem

**Comment by jazzyb** [comment]
Ah.  I see now.  I'll keep my eye on that when I investigate further.  Thanks.

**Comment by obmarg** [comment]
Tried that assertion-error branch does seem to have stopped `mix test` from crashing at least.

**Comment by mmzeeman** [comment]
Sorry, I was on a cycling/camping trip with my son without a computer. 

Thanks for making such a detailed description, I'll try to find out what is going on.

**Comment by jazzyb** [comment]
@mmzeeman I do not believe this fixes the underlying issue.  Your most recent fix now causes assertion failures for ["Attempting to destroy a non-empty queue."](https://github.com/mmzeeman/esqlite/blob/master/c_src/queue.c#L81)  I'll probably get some spare cycles this week to look into it.
