### ISSUE TITLE
New release for OTP18

### ISSUE THREAD

**Issue by hirschenberger** [mmzeeman/esqlite#21]
Would you please add a new release to hex.pm with the OTP18 fixes? Thank you.

**Comment by mmmries** [comment]
@hirschenberger I've been maintaining the hex.pm release of esqlite, have the OTP18 fixes already been merged to esqlite master? If so I can cut a release.

Also if you would like to improve the status quo here of getting esqlite released regularly you might want to see if we can setup esqlite as a community maintained hex package (https://github.com/hexpm/community)

**Comment by mmmries** [comment]
I saw that the OTP 18 stuff is merged in and is fully backwards compatible, so I went ahead and release `0.2.1` of esqlite on hex.pm https://hex.pm/packages/esqlite/0.2.1

**Comment by hirschenberger** [comment]
Thank you very much.
