### ISSUE TITLE
Use sqlite3_open_v2 to support only read mode

### ISSUE THREAD

**Issue by siscia** [mmzeeman/esqlite#30]
It could be useful to use `sqlite3_open_v2`, instead of `sqlite_open`.

In this way it will be possible to have more control in which way the database is used.

https://www.sqlite.org/c3ref/open.html

**Comment by siscia** [comment]
@mmzeeman thoughts ?

I am definitely not very suited to do this job...

I don't have much experience with erlang and definitely with writing bif module...

**Comment by mmzeeman** [comment]
This is not very difficult to do. The thing is that I currently I'm busy with: https://github.com/zotonic/zotonic/wiki/Improving-zotonic's-throughput 

PR's are welcome though.

**Comment by siscia** [comment]
Ok, I will try my best then :)

Really unsure about the result though...

**Comment by mmzeeman** [comment]
:+1:  Erlang probably isn't as scary as you think it is. . :-)

**Comment by mmzeeman** [comment]
esqlite is compiled with the SQLITE_USE_URI flag. This makes it possible to open a database in readonly mode. See https://sqlite.org/uri.html for details.
