### ISSUE TITLE
Race condition: Occasional VM crash due to dangling pointer to sqlite3_stmt struct

### ISSUE THREAD

**Issue by scouten** [mmzeeman/esqlite#34]
As mentioned in my final comment on #33, I am still seeing occasional VM crashes, though with new symptoms. The crashes I am seeing now are always segfaults (no assertion failures as in #33), and with a build instrumented to print stack traces, the crashes are always in `sqlite3_*` API functions.

I believe the following sequence of operations is happening:

1. _(scheduler thread)_ Create DB.
2. _(scheduler thread)_ Prepare a statement.
3. _(scheduler thread)_ Request information about that prepared statement (i.e. `column_names`). Queues request to command processing thread.
4. _(scheduler thread)_ Thread gets killed.
5. _(scheduler thread)_ Garbage collects statement reference, thus triggering a call to `sqlite3_finalize`.
6. _(command processing thread)_ Processes the request queued at step 3, thus triggering a call to `sqlite3_column_name` using a now-defunct pointer to `sqlite3_stmt`. *crash*

**Comment by mmzeeman** [comment]
Huh, the statement contains a reference to the db connection. The thread should not finish before the statement is destructed.

**Comment by scouten** [comment]
No, this one is different from #33 in two important ways:

1. It's not necessary for the scheduler thread to actually finish terminating before the crash happens. In fact, most of the time it didn't happen that way, which caused me a lot of confusion when first trying to track it down.
2. It's not the `sqlite3*` pointer that's dangling, but rather the `sqlite3_stmt*`. Of note: All of the crashes that I've seen have been in `sqlite3_*` API functions that take `sqlite3_stmt*` as an argument.

The problem, as I see it, is that the scheduler thread can perform garbage collection (including the call to `sqlite3_finalize`) before the command processing thread has finished performing the commands that reference that statement struct.

**Comment by mmzeeman** [comment]
Hmm, I have to think about this.

The reference to the connection is no longer needed in the prepared statement struct now that it is stored on the erlang side. I think I will adapt the api of the nif so it uses the connection passed in from the erlang.

**Comment by mmzeeman** [comment]
I cleaned up the code. The c-side statement struct no longer has a reference to the connection. This is passed in via the erlang side now. Could you check if you still see this crash occurs.

**Comment by scouten** [comment]
I do still see a crash unfortunately. Working on updating my instrumented build to better understand what's happening.

**Comment by scouten** [comment]
Hang on. That might be a false alarm. Looks like I didn't actually have the new version in place when I ran that test.

**Comment by scouten** [comment]
No. Definitely still crashing with segfault in the `sqlite3_*` functions as before. The interesting (new) thing that I'm seeing is that I don't think `esqlite_destruct_statement` ever gets called.

What's odd is that if that were true, I'd expect that the crashes (if any) would look different than before. (In other words, I'd expect a memory leak, not a dangling pointer.) But they don't; it still looks like `sqlite3_*` functions are dereferencing bad pointers to `sqlite3_stmt*`. I haven't figured out what, if anything, is releasing or corrupting the `sqlite3_stmt*` struct.

I'll dig more into it tomorrow.

In the meantime, my crash harness (https://github.com/scouten/crash_esqlite_case) is updated with latest code.

**Comment by mmzeeman** [comment]
BTW, it is better to use fprintf(stder, ... ) otherwise the prints will have a different order because of buffering.

**Comment by mmzeeman** [comment]
I've added a test to check if sqlite3 is build in thread-safe mode when opening a database.

**Comment by mmzeeman** [comment]
I think I found something. 

```
destruct_esqlite_statement stmt = 00007f0534013288

... stuff omitted...

esqlite_connection_run tid = 00007f056d73f700, conn = 00007f0575dce9d8 queue = 00007f057ca82658, db = 00007f05340008c8 command thread eval command 8
esqlite_connection_run tid = 00007f056d73f700, conn = 00007f0575dce9d8 queue = 00007f057ca82658, db = 00007f05340008c8 command thread eval command 8. Evaluating command
do_column_names stmt = 00007f0534013288
```

The statement is destructed, but there is still a prepared statement on the queue...  

Which is very strange because that means there is something waiting for the answer from the db, so the statement should not be destructed.

**Comment by mmzeeman** [comment]
I Found the problem... I can now run your test suite without signal 11's.

The command should have gotten a copied reference to the statement. The same should be done with the db connection. These should not be passed as sqlite pointers to the thread, but passed as erlang terms.

```
--------- Attempt 99 ---------
Excluding tags: [:array_type, :strict_savepoint, :update_with_join, :delete_with_join, :foreign_key_constraint, :modify_column, :modify_foreign_key, :prefix, :remove_column, :rename_column, :right_join, :unique_constraint, :uses_usec, :insert_cell_wise_defaults]

begin_test_transaction
restart_test_transaction
.rollback_test_transaction


Finished in 0.1 seconds
1 test, 0 failures

Randomized with seed 589319

--------- Attempt 100 ---------
Excluding tags: [:array_type, :strict_savepoint, :update_with_join, :delete_with_join, :foreign_key_constraint, :modify_column, :modify_foreign_key, :prefix, :remove_column, :rename_column, :right_join, :unique_constraint, :uses_usec, :insert_cell_wise_defaults]

begin_test_transaction
restart_test_transaction
rollback_test_transaction
.

Finished in 0.1 seconds
1 test, 0 failures

Randomized with seed 29355
```

**Comment by scouten** [comment]
Well, you've made it _harder_ to crash. 🙂 

I ran 1000 iterations of the `try-to-crash.sh` script on my (Mac) laptop and has no crashes. I then submitted a pull request to sqlite_ecto2 to incorporate this build and two of the Travis CI builds (Debian) failed with segfaults. 

The latest (where it's in master branch) is at: https://travis-ci.org/scouten/sqlite_ecto2/jobs/206816118

I will run through my annotated build later today to see if I can understand this latest.

**Comment by scouten** [comment]
Hang on. I copied the wrong commit ID into sqlite_ecto2. Re-running now with your current master.

**Comment by scouten** [comment]
🎉 🎉 :tada:

Looks like we have a good build!

Thank you!!!

**Comment by scouten** [comment]
Closed by c1ba116de470aadc23e7ae582c961b2ced13d306.

**Comment by mmzeeman** [comment]
Thank you too. And Ecto2's test routines. 

This is probably the first stable release of esqlite.

**Comment by mmmries** [comment]
@mmzeeman I'll re-release to hex.pm, but just wanted to offer again to transfer the package to you if you want to take over it. The only reason I currently own it is because I wanted to make it easy for other people to pull it in as a rebar3 or hex dependency.

**Comment by mmzeeman** [comment]
@mmmries Oh, ok, thanks for maintaining it. At the moment I'm not really looking into doing more work. At the moment I'm not even using esqlite in production. Although that is going to change soon.
