### ISSUE TITLE
Fatal error C1083: Cannot open include file: 'stdlib.h': No such file or directory

### ISSUE THREAD

**Issue by thiagomajesk** [mmzeeman/esqlite#38]
**From:** https://github.com/scouten/sqlite_ecto2/issues/206

Hello, I'm compiling esqlite3_nif.c on Windows 10 using VisualCppBuildTools 14.0.25420.1 (Chocolatey Package):

```
c:\Program Files\erl9.3\erts-9.3\include\erl_nif.h(71): fatal error C1083: Cannot open include file: 'stdlib.h': No such file or directory

** (Mix) Could not compile dependency :esqlite, "escript.exe "c:/Users/usr/.mix/rebar3" bare compile --paths "c:/Users/usr/Desktop/proj/_build/dev/lib/*/ebin"" command failed. 
You can recompile this dependency with "mix deps.compile esqlite", update it with "mix deps.update esqlite" or clean it with "mix deps.clean esqlite"
```

**Comment by Razzeee** [comment]
Were you able to solve this? I'm hitting the same problem on windows, linux seems to work fine.

**Comment by thiagomajesk** [comment]
@Razzeee Unfortunately no. Since I've moved away from elixir temporarily I haven't tried anything else to solve this. Maybe a good place to seek for help is the [official forum](https://elixirforum.com/). 
If you manage to get any help there, please come back and give your feedback.

**Comment by Razzeee** [comment]
Here's an update.
I installed visual studio 2017 community and started `Developer Command Prompt` then I can compile it correctly in that prompt. As the file get's cached I can then use my normal commandline.

Not really happy with this, but at least I can use my environment again.

**Comment by thiagomajesk** [comment]
@Razzeee I have stumbled uppon this repo today: [sqlitex](https://github.com/Sqlite-Ecto/sqlitex). 
It seems to be a wrapper around esqlite, but idk if we would still have to compile something manually.

**Comment by Razzeee** [comment]
You have, that's what I'm using if my memory is not fooling me. (would have to check on the work pc)

**Comment by x-ji** [comment]
You need to load the compiler correctly. See https://stackoverflow.com/questions/43372235/vcvarsall-bat-for-visual-studio-2017

I executed the command in the top answer and then was able to execute it correctly. However I met `unspecified_error` bug when I tried to run the app: https://github.com/mmzeeman/esqlite/issues/29#issuecomment-446402225
