### ISSUE TITLE
insert with parameters and get autoincrement value

### ISSUE THREAD

**Issue by brigadier** [mmzeeman/esqlite#44]
I don't see a way to execute a parametrized insert and get value of the autoincremented PK. There's either a parametrized `prepare/bind/step` which returns '$done' or non-parametrized `insert` which is dangerous to use because of possible SQL injection. Am I missing something?

**Comment by mmmries** [comment]
@brigadier you might want check how the sqlite ecto team tackled this problem. https://github.com/jazzyb/sqlite_ecto/wiki/Sqlite.Ecto's-Pseudo-Returning-Clause

**Comment by mmmries** [comment]
Although most people seem to just use the `sqlite3_last_insert_rowid` for this purpose. So that might be simpler than how the ecto people solved it.
