### ISSUE TITLE
Investigate server-process-edition branch.

### ISSUE THREAD

**Issue by fire** [mmzeeman/esqlite#45]
https://sqlite.org/src/timeline?r=server-process-edition

[html readme](https://sqlite.org/src/raw/README-server-edition.html?name=b98409c486d6f02871b20a9e29e1e18cd050a02e03062569ffb051774b4d6861)

https://news.ycombinator.com/item?id=17766799

Appears to be a performance improvement.

**Comment by mmzeeman** [comment]
That is an interesting development. Looking into it.

**Comment by mmzeeman** [comment]
This seems like a dead end in sqlite's development. Closing the issue, but thangs for pointing me to it.
