### ISSUE TITLE
mix deps.compile esqlite fails while linking esqlite3_nif.so on ARM

### ISSUE THREAD

**Issue by duck57** [mmzeeman/esqlite#63]
Specifically, it's a Raspberry Pi 4 where this is failing.

The exact error message is:

`** (Mix) Could not compile dependency :esqlite, "/home/pi/.mix/rebar3 bare compile --paths="/home/pi/Documents/programming stubs/friends/_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile esqlite", update it with "mix deps.update esqlite" or clean it with "mix deps.clean esqlite"`

What can I do to fix this and make it compile?

**Comment by mmzeeman** [comment]
Sorry, I don't have a clue. I'm not a mix user myself.

**Comment by ConnorRigby** [comment]
@duck57 this was an issue with the rebar plugin and nerves. I have a fix for it. I'll push it up and pull request this repo on the next few days. Sorry about this.

**Comment by jthacker** [comment]
@ConnorRigby I'm experiencing the same issue. Did you get a chance to work on the PR for this? Or have any tips for resolving it?

@duck57 Were you able to workaround the issue?

**Comment by ConnorRigby** [comment]
Really sorry about this. I haven't had time to update the rebar plugin. For a temporary workaround, you can try this:

* add this Makefile to your project:
https://github.com/FarmBot/farmbot_os/blob/13ae06cf173ec5802ffebedc7dfb7aac9cd94b1b/farmbot_os/Makefile
* and then make these changes to your mixfile:
https://github.com/FarmBot/farmbot_os/blob/13ae06cf173ec5802ffebedc7dfb7aac9cd94b1b/farmbot_os/mix.exs#L24
https://github.com/FarmBot/farmbot_os/blob/13ae06cf173ec5802ffebedc7dfb7aac9cd94b1b/farmbot_os/mix.exs#L63

**Comment by Qqwy** [comment]
We are encountering a problem that is probably related if not identical. Cross-compiling on an x86-64 system for ARM and then moving the files (or rather the final mix release) seems to work, but compiling the source directly on an ARM device fails.

**Comment by mmzeeman** [comment]
Could this be related to: #64?

**Comment by mmzeeman** [comment]
Bumbed rebar3 to version 3.14.1
