### ISSUE TITLE
Erlang/OTP 23 /usr/bin/ld: cannot find -lerl_interface

### ISSUE THREAD

**Issue by dominicletz** [mmzeeman/esqlite#64]
Linking seems to fail with rebar3 defaults on Erlang/OTP 23 as they have removed erl_interface.so from the shipped bundle. 

See https://www.erlang.org/news/140

I had to manually work around with a new Makefile. Not sure though if just removing the erl_interface dependency works on older versions of OTP..

**Comment by dominicletz** [comment]
Ah seems the new rebar3 version 3.14.0 will actually fix that https://github.com/erlang/rebar3/issues/2323 -- so pls update https://github.com/mmzeeman/esqlite/blob/2fdd5834ad774a34ae5d038fbb2a28fae3a88bad/Makefile#L5 once 3.14.0 is released and compilation should work again

**Comment by mmzeeman** [comment]
Bumped rebar3 to version 3.14.1
