### ISSUE TITLE
`exec` return type is `integer() |  {error, error_message()}` but returns `ok | {error, error_message()}`

### ISSUE THREAD

**Issue by lud** [mmzeeman/esqlite#65]
I don't know how Clang works, let alone erlang nifs, but I can see that there is a `do_exec` function whose last line is:

```
return make_atom(env, "ok");
```

So, I guess we may just change the return types. Although, having the actual number of affected rows could be great. (in an ok tuple)

**Comment by mmzeeman** [comment]
Fixed.

**Comment by lud** [comment]
Thanks !
