### ISSUE TITLE
enif_alloc_env one msg_env, after use to send msg but not enif_free_env

### ISSUE THREAD

**Issue by SisMaker** [mmzeeman/esqlite#82]
i see the code found in the 'esqlite3_nif.c' and the 'update_callback' fun use enif_alloc_env to alloc one env to send msg but not enif_free_env. it is seem reource leak

**Comment by mmzeeman** [comment]
Thanks, will check it later today.

**Comment by mmzeeman** [comment]
Thanks @SisMaker this was indeed an issue.
