### ISSUE TITLE
esqlite return "error = 21"

### ISSUE THREAD

**Issue by Zabrane** [mmzeeman/esqlite#87]
Hi @mmzeeman 

We switched to the latest `esqlite` version yesterday (we were previously using `0.8.6` for years) and we started getting the following error:
![esqlite_error_21](https://github.com/mmzeeman/esqlite/assets/532544/9b0de1ec-b704-414f-b980-1607f4e9a515)

This happens sporadically and under almost no load (not even during concurrent writes).
Do you have any idea what can lead to this?
Many thanks 

```bash
. Erlang 26.1.2
. rebar 3.22.0 on Erlang/OTP 26 Erts 14.0.2
. OS: macOS Sonoma | Ubuntu 22.04 LTS
```

**Comment by Zabrane** [comment]
@mmzeeman thanks a lot, that was it. The new version is much faster and the process who opens the DB originally closes it earlier than before. 
Keep up the work ;-)

**Comment by mmzeeman** [comment]
👍 

Thanks for your reply... It is always nice to hear from people using this library.
