### ISSUE TITLE
Sporadic read latencies

### ISSUE THREAD

**Issue by Zabrane** [mmzeeman/esqlite#88]
Hi @mmzeeman 

We're noticing  random/sporadic `read latencies` on some simple queries:
```sql
SELECT id FROM docs WHERE ((user = 'john.doe') AND (((status = 'draft') OR (status = 'onhold')) OR (status = 'onprogress'))) ORDER BY creation_ts DESC LIMIT 201125, 5;
```

On average, this request takes `190 ms`, but occasionally it can take up to `600 ms`.

1. Any idea what causes this behavior?
2. New `esqlite` uses `Dirty scheduler`: could this be the problem?
3. How can we mitigate these read latencies?

Config:
. Erlang (macOS + Ubuntu 22.04 LTS): `26.2.3`
. esqlite: `0.8.6`

Help appreciated

**Comment by mmzeeman** [comment]
I haven't really done any profiling for things like these.

Do you have a test setup so I can take a look?

Maybe one of the functions of the NIF need a `ERL_NIF_DIRTY_JOB_CPU_BOUND` or `ERL_NIF_DIRTY_JOB_IO_BOUND` flag.

**Comment by Zabrane** [comment]
@mmzeeman unfortunately no test data for now. Can you please tell me which functions I should test (ERL_NIF_DIRTY_JOB_CPU_BOUND + ERL_NIF_DIRTY_JOB_IO_BOUND) first?

**Comment by mmzeeman** [comment]
I assumed all functions which open/close and do query processing are io bound, but maybe that is not the case in practice. 

I haven't tested this, it was just my best effort assumption. 

Having a representative dataset combined with some sort of workload on the node will probably help to improve. 👍

**Comment by mmzeeman** [comment]
Would it be an idea to use the sample database found here: https://github.com/lerocha/chinook-database/tree/master and get some query timings under some sort of load and check the request times and standard deviation?

**Comment by Zabrane** [comment]
Hi @mmzeeman 

Here you are:
```sql
$ gunzip slow_db.sqlite.gz
$ sqlite3 ./slow_db.sqlite
```

Then:
```sql
SELECT id FROM purchases WHERE ((user = 'bernard') AND (((status = 0) OR (status = 2)) OR (status = 1))) ORDER BY creation_ts DESC LIMIT 200015, 5;
```

The database is pretty big (138MiB uncompressed) and GitHub limits upload to 25MiB.
You can download it from here:
https://we.tl/t-5OuKaSeb8r

Let me know if you need anything else.
Thanks

**Comment by Zabrane** [comment]
> Would it be an idea to use the sample database found here: https://github.com/lerocha/chinook-database/tree/master and get some query timings under some sort of load and check the request times and standard deviation?

@mmzeeman Very good idea. Didn't know about `chinook` database before. Thanks for sharing.

**Comment by mmzeeman** [comment]
I wonder if it could be some kind of caching inside sqlite itself.

I see the increased read latency mostly after a bit of time has passed.

```
147> timer:tc(esqlite3,q, [Conn, "SELECT id FROM purchases WHERE ((user = 'bernard') AND (((status = 0) OR (status = 2)) OR (status = 1))) ORDER BY creation_ts DESC LIMIT 200015, 5;"]).
{409850,
 ...
148> timer:tc(esqlite3,q, [Conn, "SELECT id FROM purchases WHERE ((user = 'bernard') AND (((status = 0) OR (status = 2)) OR (status = 1))) ORDER BY creation_ts DESC LIMIT 200015, 5;"]).
{204779,
 ...
```

**Comment by mmzeeman** [comment]
It sure is strange. If you set caching to 0 you get similar behavior, with occasional long latencies. So I think it isn't SQLite caching either. It could also be the os level disk cache.

**Comment by Zabrane** [comment]
@mmzeeman when trying the DB in RAM only, there is no occasional latencies.
Everything is super stable.

**Comment by mmzeeman** [comment]
Good to hear. So it is something out of the scope of the sqlite nif.

**Comment by Zabrane** [comment]
@mmzeeman definitely not a NIF issue.
Keep up the good work and many thanks for your support.
